let pageCheck = 0;
let pageCount ;
const products = [
    {
        "id":1,
        "name":"چیپس چاکلز",
        "image":"./img/product1.jpg",
        "description":"چیپس سیب زمینی 60 گرمی چاکلز",
        "type":"سوپر مارکت",
        "price":25000,
    },
    {
        "id":2,
        "name":"چیپس مزمز",
        "image":"./img/product2.jpg",
        "description":"چیپس سیب زمینی 60 گرمی مزمز",
        "type":"سوپر مارکت",
        "price":27000,
    },
    {
        "id":3,
        "name":"پفک چیتوز",
        "image":"./img/product3.jpg",
        "description":"پفک 40 گرمی چیتوز موتوری",
        "type":"سوپر مارکت",
        "price":30000,
    },
    {
        "id":4,
        "name":"بیسکوییت ساقه طلایی",
        "image":"./img/product4.jpg",
        "description":"بیسکوییت 200 گرمی ساقه طلایی",
        "type":"سوپر مارکت",
        "price":32000,
    },
    {
        "id":5,
        "name":"تخم مرغ",
        "image":"./img/product5.jpg",
        "description":"تخم مرغ زرین پر 9 عددی",
        "type":"سوپر مارکت",
        "price":56000,
    },
    {
        "id":6,
        "name":"نودل الیت",
        "image":"./img/product6.jpg",
        "description":"نودل الیت سبزیجات 75 گرمی",
        "type":"سوپر مارکت",
        "price":24000,
    },
    {
        "id":7,
        "name":"کت مردانه زاگرس",
        "image":"./img/product7.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":8,
        "name":"دامن زنانه هیبا",
        "image":"./img/product8.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":9,
        "name":"کفش پوما",
        "image":"../img/product9.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":10,
        "name":"مانتو بلوچ",
        "image":"../img/product10.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":11,
        "name":"شومیز جین وست",
        "image":"../img/product11.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":12,
        "name":"شلوار جین ماوی",
        "image":"../img/product12.jpg",
        "description":"",
        "type":"پوشاک",
        "price":25000,
    },
    {
        "id":13,
        "name":"گوشی سامسونگ s20",
        "image":"../img/product13.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
    {
        "id":14,
        "name":"هندزفری بیسیم اپل",
        "image":"../img/product14.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
    {
        "id":15,
        "name":"شارژر سامسونگ",
        "image":"../img/product15.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
    {
        "id":16,
        "name":"فلش مموری 16Gb",
        "image":"../img/product16.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
    {
        "id":17,
        "name":"ساعت هوشمند اپل",
        "image":"../img/product17.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
    {
        "id":18,
        "name":"هدست JBL",
        "image":"../img/product18.jpg",
        "description":"",
        "type":"الکترونیک",
        "price":25000,
    },
]